publishDir = "docs"

baseURL = "http://phonicfactory.github.io/hallo"
languageCode = "en-us"
title = "The Phonic Factory - We Create Conversations"
theme = "hallo"

[Author]
    name = "Phonic Factory"

[params]
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/PhonicFactory"
    [[params.links]]
        icon = "envelope"
        title = "E-mail"
        url = "mailto:brad@phonicfactory.com"
